/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { ArgsType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { MindMapWhereUniqueInput } from "./MindMapWhereUniqueInput";
import { ValidateNested } from "class-validator";
import { Type } from "class-transformer";
import { MindMapUpdateInput } from "./MindMapUpdateInput";

@ArgsType()
class UpdateMindMapArgs {
  @ApiProperty({
    required: true,
    type: () => MindMapWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => MindMapWhereUniqueInput)
  @Field(() => MindMapWhereUniqueInput, { nullable: false })
  where!: MindMapWhereUniqueInput;

  @ApiProperty({
    required: true,
    type: () => MindMapUpdateInput,
  })
  @ValidateNested()
  @Type(() => MindMapUpdateInput)
  @Field(() => MindMapUpdateInput, { nullable: false })
  data!: MindMapUpdateInput;
}

export { UpdateMindMapArgs as UpdateMindMapArgs };
