/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsString,
  MaxLength,
  IsOptional,
  IsInt,
  Min,
  Max,
  ValidateNested,
} from "class-validator";
import { FlashcardUpdateManyWithoutPdfsInput } from "./FlashcardUpdateManyWithoutPdfsInput";
import { Type } from "class-transformer";
import { MindMapUpdateManyWithoutPdfsInput } from "./MindMapUpdateManyWithoutPdfsInput";
import { QuestionUpdateManyWithoutPdfsInput } from "./QuestionUpdateManyWithoutPdfsInput";
import { SummaryUpdateManyWithoutPdfsInput } from "./SummaryUpdateManyWithoutPdfsInput";

@InputType()
class PdfUpdateInput {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  fileName?: string | null;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsInt()
  @Min(-999999999)
  @Max(999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  fileSize?: number | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  fileUrl?: string | null;

  @ApiProperty({
    required: false,
    type: () => FlashcardUpdateManyWithoutPdfsInput,
  })
  @ValidateNested()
  @Type(() => FlashcardUpdateManyWithoutPdfsInput)
  @IsOptional()
  @Field(() => FlashcardUpdateManyWithoutPdfsInput, {
    nullable: true,
  })
  flashcards?: FlashcardUpdateManyWithoutPdfsInput;

  @ApiProperty({
    required: false,
    type: () => MindMapUpdateManyWithoutPdfsInput,
  })
  @ValidateNested()
  @Type(() => MindMapUpdateManyWithoutPdfsInput)
  @IsOptional()
  @Field(() => MindMapUpdateManyWithoutPdfsInput, {
    nullable: true,
  })
  mindMaps?: MindMapUpdateManyWithoutPdfsInput;

  @ApiProperty({
    required: false,
    type: () => QuestionUpdateManyWithoutPdfsInput,
  })
  @ValidateNested()
  @Type(() => QuestionUpdateManyWithoutPdfsInput)
  @IsOptional()
  @Field(() => QuestionUpdateManyWithoutPdfsInput, {
    nullable: true,
  })
  questions?: QuestionUpdateManyWithoutPdfsInput;

  @ApiProperty({
    required: false,
    type: () => SummaryUpdateManyWithoutPdfsInput,
  })
  @ValidateNested()
  @Type(() => SummaryUpdateManyWithoutPdfsInput)
  @IsOptional()
  @Field(() => SummaryUpdateManyWithoutPdfsInput, {
    nullable: true,
  })
  summaries?: SummaryUpdateManyWithoutPdfsInput;
}

export { PdfUpdateInput as PdfUpdateInput };
