/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { StringNullableFilter } from "../../util/StringNullableFilter";
import { Type } from "class-transformer";
import { IsOptional, ValidateNested } from "class-validator";
import { IntNullableFilter } from "../../util/IntNullableFilter";
import { FlashcardListRelationFilter } from "../../flashcard/base/FlashcardListRelationFilter";
import { StringFilter } from "../../util/StringFilter";
import { MindMapListRelationFilter } from "../../mindMap/base/MindMapListRelationFilter";
import { QuestionListRelationFilter } from "../../question/base/QuestionListRelationFilter";
import { SummaryListRelationFilter } from "../../summary/base/SummaryListRelationFilter";

@InputType()
class PdfWhereInput {
  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  fileName?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: IntNullableFilter,
  })
  @Type(() => IntNullableFilter)
  @IsOptional()
  @Field(() => IntNullableFilter, {
    nullable: true,
  })
  fileSize?: IntNullableFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  fileUrl?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: () => FlashcardListRelationFilter,
  })
  @ValidateNested()
  @Type(() => FlashcardListRelationFilter)
  @IsOptional()
  @Field(() => FlashcardListRelationFilter, {
    nullable: true,
  })
  flashcards?: FlashcardListRelationFilter;

  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  id?: StringFilter;

  @ApiProperty({
    required: false,
    type: () => MindMapListRelationFilter,
  })
  @ValidateNested()
  @Type(() => MindMapListRelationFilter)
  @IsOptional()
  @Field(() => MindMapListRelationFilter, {
    nullable: true,
  })
  mindMaps?: MindMapListRelationFilter;

  @ApiProperty({
    required: false,
    type: () => QuestionListRelationFilter,
  })
  @ValidateNested()
  @Type(() => QuestionListRelationFilter)
  @IsOptional()
  @Field(() => QuestionListRelationFilter, {
    nullable: true,
  })
  questions?: QuestionListRelationFilter;

  @ApiProperty({
    required: false,
    type: () => SummaryListRelationFilter,
  })
  @ValidateNested()
  @Type(() => SummaryListRelationFilter)
  @IsOptional()
  @Field(() => SummaryListRelationFilter, {
    nullable: true,
  })
  summaries?: SummaryListRelationFilter;
}

export { PdfWhereInput as PdfWhereInput };
